config/routes.rb
Rails.application.routes.draw do
  get 'bears' => 'application#bears', as: 'bears'
  get 'bulls' => 'application#bulls', as: 'bulls'
  root to: 'application#index'
end

app/models/bear.rb
class Bear < ActiveRecord::Base
end

app/models/bull.rb
class Bull < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def bears
    @bears = Bear.pluck(:name).sort
  end

  def bulls
    Octopus.using(:mssql) do
      @bulls = Bull.pluck(:name).sort
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/bears.html.slim
h1 Bears

.post.panel.panel-default
  .panel-body
    p This page queries local database, if You see `-mssql` suffix of name this means that mssql database queried.
    ul
    - @bears.each do |name|
      li= name

app/views/application/bulls.html.slim
h1 Bulls

.post.panel.panel-default
  .panel-body
    p This page queries mssql database, if You don't see `-mssql` suffix of name this means that local database queried.
    ul
    - @bulls.each do |name|
      li= name

app/views/application/index.html.slim
h1 Loqqo

p This is example application which connects to local database (postgres) and external database - mssql, deployed to heroku

p Both local and mssql database have same structure but mssql database has been seeded with "-mssql" suffix added to names. "Bears" page queries localdatabase and names in the list should not contain that suffix. "Bulls" page vice versa queries mssql database and names in the list SHOULD contain suffix.

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
li = link_to 'Bears', bears_path
li = link_to 'Bulls', bulls_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Loqqo'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Loqqo'}"
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield